services:
  - type: web
    name: zonat-steal-v3
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        value: 8075320326:AAHVxtnOER6Ud8VSXxU9ApAtsz3-boeDQPk
      - key: ADMIN_ID
        value: "7725796090"
      - key: WEBHOOK_BASE
        value: "https://artursaoo.onrender.com"
    plan: free
